language: java
jobs:
  allow_failures:
    - os: osx
script: 
 
 mvn clean package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=superdevsteph -Dsonar.login=18ce5e8923375cbc12d33f5023750cd46ea6e46f
